### ISSUE TITLE
Explore authentication

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#11]
Explore authentication using Google or Facebook, storing some credentials and how it works with Firebase/Firestore (#2). Both on web and mobile. In Dart, of course.

We will choose the Google login, but is it worth it to use FB too? Is it easy to set up etc.?

Is there any other popular login service?

* [ ] Google web 
* [ ] Google mobile
* [x] FB web
* [x] FB mobile

**Comment by vojtechdalecky** [comment]
I have started studying it. It doesn't seem to be that difficult (yet). 👏

**Comment by vojtechdalecky** [comment]
I talked about FB auth with other team members and we think, that we dont need it, google auth is enough for our purpose. ✌️

**Comment by tenhobi** [comment]
I agree.

**Comment by tenhobi** [comment]
I need it for the landing page NOW, so I will explore this myself. 🔥

**Comment by tenhobi** [comment]
https://www.youtube.com/watch?v=8M-Fa239Hy4&index=30&list=PLR2qQy0Zxs_UdqAcaipPR3CG1Ly57UlhV

Link https://pub.dartlang.org/packages/firebase_auth

This is very simple. Look for thing in #57 for understand. I will create some API for it there.
