### ISSUE TITLE
Analysis of business processes

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#13]
* [x] diagramy aktivit (UML Behavioral-Activity)
* [x] textové popisy procesů
* [x] přeorganizovat wiki aby vše dávalo smysl (procesy, požadavky funkční & nefunkční)

Vše dávat na wiki.

**Comment by tenhobi** [comment]
https://edux.fit.cvut.cz/courses/BI-SI1/_media/lectures/02/02.prednaska.pdf

**Comment by tenhobi** [comment]
@stasidom I am going to write down some description of processes in a few hours so you can create a diagram for it. 👍

**Comment by stasidom** [comment]
@tenhobi Did you find out in which sense I should do the analysis? For example the behavioral of the final app or if it should be about how we are gonna proceed in development of the app?

**Comment by tenhobi** [comment]
In the slides there is 'diagram activit' shown as this

![image](https://user-images.githubusercontent.com/5287596/37116694-54d53e3c-224f-11e8-90a9-5693729c5980.png)

So it's probably not about our developing, but about the app process. So you can work on top of use cases, I guess. https://github.com/tenhobi/flashcards/wiki/1st-iteration-of-BI-SP1#use-cases

**Comment by tenhobi** [comment]
But we will have only one subject for each diagram. So in one diagram there will be only "user", in another there will be only "author" etc. Dunno. ¯\_(ツ)_/¯

**Comment by tenhobi** [comment]
![image](https://user-images.githubusercontent.com/5287596/37117177-c3996c8e-2250-11e8-8629-b2c7166cbede.png)

**Comment by tenhobi** [comment]
My friend did this on their project. So we can do diagram with user & app.

![28832478_10209262875727887_226172079_n](https://user-images.githubusercontent.com/5287596/37118059-3f55903a-2253-11e8-83df-ff5dbb0e2956.jpg)

**Comment by stasidom** [comment]
Yeah, I have thought it should be like this. So I will make a diagram for each UC we have? If I get it right.

**Comment by tenhobi** [comment]
Yes, probably. If it can be combined, do it. So maybe one diagram per functional requirment would be possible to do. Dunno.

**Comment by tenhobi** [comment]
@stasidom Finish this task, please, this weekend. :-)

**Comment by stasidom** [comment]
It will be finished today.

**Comment by stasidom** [comment]
![student_process](https://user-images.githubusercontent.com/29426904/37687497-0d32893e-2c9c-11e8-95f4-305723f76652.PNG)
