### ISSUE TITLE
Analytical domain model of classes

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#15]
* [x] analytický (doménový) model tříd
* [ ] diagram tříd - kardinality, názvy asociací (UML Structural-Class)
* [ ] popisy jednotlivých entit a jejich atributů
* [ ] stavový diagram pro vybrané entity (UML Behavioral-State Machine)

**Comment by Kenny11CZ** [comment]
Any suggestions/improvments/whatever?
[Link to project source](https://repository.genmymodel.com/Kenny11CZ/FlashCardsDM)
[Zip with XMI file](https://github.com/tenhobi/flashcards/files/1752230/FlashCardsDM.1.zip)
![image](https://user-images.githubusercontent.com/8071168/36602506-7fdfd3d0-18b8-11e8-9ae1-115bd255aa06.png)

**Comment by tenhobi** [comment]
Questions could have text, image and sound as a list. + text question could have case sensitive bool property.

**Comment by tenhobi** [comment]
Web and social links should be merged into `List<Tuple2<String, String>> links`. (https://pub.dartlang.org/packages/tuple)

**Comment by Kenny11CZ** [comment]
I totally forgot about the second one, whopsie.

**Comment by tenhobi** [comment]
And we should simplify the Material into just a String property in Section.

**Comment by Kenny11CZ** [comment]
Link remains unchanged.
v2
![image](https://user-images.githubusercontent.com/8071168/36603346-bc475792-18ba-11e8-961a-36634ff53052.png)

**Comment by tenhobi** [comment]
Oops, I have meant to use List for the current 'definition' in Question.

The "object" (simple text, picture or sound) should be one only:

object: [definitions...]
/flag of Czechia/: ['flag of Czechia', 'flag of Czech republic', 'Czechia', 'Czech republic']

**Comment by michaldrabina** [comment]
Shouldn't the first part of the link tuple be some kind of enum instead of string?

**Comment by tenhobi** [comment]
Nope, it should be in the form `name of the link : link`, e.g. `Tuple2('GitHub', 'https://...')`, but you can also do something like `Tuple2('SomeUnknownSite', 'http://...')`.

**Comment by michaldrabina** [comment]
Wouldn't it be better to have enum, with supported sites + other? I thought we are gonna have a dropbox of sites we support with icons for each of them.

**Comment by tenhobi** [comment]
We can still have icons for "supported sites", but making an enum for this is just an unnecessary work with no effect.

**Comment by michaldrabina** [comment]
So you want to compare strings instead?

**Comment by tenhobi** [comment]
Checking if some url contains "github" etc. is a work for "no price" for us. (`myVariable.contains('github')`)

On the other hand, having an unnecessary interface is kinda messy + it will not bring any value.

Therefore I prefer the first solution.

**Comment by michaldrabina** [comment]
After internal discussion we decided it's gonna be tuple<int, string>.

**Comment by tenhobi** [comment]
Just a report from the Discord conversation: we will stick with `tuple<enum, url>`, e.g. `tuple<int, string>`, probably with some limit of 5 or so, but that is not relevant for this task.

**Comment by Kenny11CZ** [comment]
Final version?
![obrazek](https://user-images.githubusercontent.com/8071168/36635095-a18bba56-19af-11e8-8d38-2a54bf8dd0e9.png)

**Comment by Kenny11CZ** [comment]
![obrazek](https://user-images.githubusercontent.com/8071168/36635330-25c63a46-19b3-11e8-98b0-89729c7d5ff1.png)

**Comment by tenhobi** [comment]
In the presentation there is the rule, that the class in this model should not contains attributes specific for implementation, so we should probably remove `id` and `googleId` from `User`?

**Comment by tenhobi** [comment]
Also, the Question class should have attribute explanation (markdown string).

**Comment by Kenny11CZ** [comment]
Is this okey @tenhobi ?
![image](https://user-images.githubusercontent.com/8071168/37209145-65bb09d8-23a4-11e8-97c9-78c7943f4579.png)

**Comment by tenhobi** [comment]
This looks ok for our purpose. Add a description to the wiki for each entity. 👍 

We may ommit the rest, I don't see much sense in that.

**Comment by Kenny11CZ** [comment]
Decription done, this domain model image added, please review it [here](https://user-images.githubusercontent.com/8071168/37209145-65bb09d8-23a4-11e8-97c9-78c7943f4579.png).
Closing this isssue.
