### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#17]
* [ ] databázový model - diagram tříd (UML Structural-Class)/alternativně detailní popis rozhraní, které bude používáno pro načítní/ukládání dat, pokud aplikace nemá vlastní databázi
* [ ] primární klíče
* [ ] cizí klíče
* [ ] datové typy
* [ ] dekompozice m:n vazeb

**Comment by vojtechdalecky** [comment]
Not in english ? Should i translate it, or you want to do it yourself ?

**Comment by tenhobi** [comment]
@vojtechdalecky you can translate this issue's description if you want. But it's only nice to have thing.
