### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#22]
@Kenny11CZ We should decide what CI/CD app to use.

I vote for Travis CI, since it's open source and we can use it unlimited until eternity. But I know you wanna try out the TeamCity. What about use both? We will set up Travis CI and connect it to GitHub pull requests etc. and you can set up TeamCity to this public repository (will be) and test it out? :-)

**Comment by Kenny11CZ** [comment]
I agree with you, we can setup both. You will take Travis and I'll take TC.

**Comment by tenhobi** [comment]
Static analysis of logic, angular and flutter is set up in Travis.

**Comment by tenhobi** [comment]
I have been trying to set up more cleaner config for Travis CI (#25) and it works, but only for one Dart version, not for all. Currently I am seeking for a solution of that.

**Comment by tenhobi** [comment]
We will probably just leve it for now with only stable version checked.
