### ISSUE TITLE
Screen orientation

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#32]
We have to set the app so it ~can be rotated. (it may be default, but we should set it explicitly, but only if the user didn't forbit it)~ only allows the portrait mode.

* [x] Android
* [x] iOS

~Use the #33 branch for commiting.~

**Comment by vojtechdalecky** [comment]
I think its too soon for this. I dont even know, if i want our app to rotate. I can take a look at it on iOS later (much later).

**Comment by tenhobi** [comment]
@vojtechdalecky so explore how to set to rotate (only if the user allows it)—in android it's `fullUser`—and how to disale rotation. ;)

**Comment by Kenny11CZ** [comment]
So, we want it to be in landscape or portrait mode? I think it's better to choose only one, so we don't have to tweak stuff and it will be more consistent. For example [Dobyvatel](https://play.google.com/store/apps/details?id=air.com.triviador.trcz) is only in landscape mode, on the other hand [Memrise](https://play.google.com/store/apps/details?id=com.memrise.android.memrisecompanion) is only (atleast i hope so) in portrait mode. Landscape is better for user, most phones are just better when hold with both hands, especially bigger ones, but there's usually a lot of unused space (Dobyvatels case).

**Comment by tenhobi** [comment]
Duolingo has both.

**Comment by Kenny11CZ** [comment]
I suggest to stick to the portrait only mode, since we don't have time to create landscape wireframes and implement them, and for purposes of this application it's sufficient, i think.

**Comment by tenhobi** [comment]
I cannot see an issue with landscape. Plus implementing that is very fast, often even with no effort.

**Comment by tenhobi** [comment]
@Kenny11CZ will we do only portrait mode then? I will switch the android version, @vojtechdalecky should switch the ios. Meaning allow only portrait mode.

**Comment by tenhobi** [comment]
Use #126, pls.

**Comment by tenhobi** [comment]
We will move this to the 3rd iteration, when we decide what to do.
