### ISSUE TITLE
Flutter errored in Travis CI

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#40]
Examine why Travis started throwing an error for Flutter: `ERR : Package flashcards_flutter requires Flutter SDK version ^0.1.2 but the current SDK is 0.2.1-pre.39.`

**Comment by Kenny11CZ** [comment]
You can try change from semantic versioning to [this one](https://www.dartlang.org/tools/pub/versioning#version-constraints) or upgrade dependencies, we have no code that could break yet.
