### ISSUE TITLE
Graphics to release

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#98]
* [x] App icons
* [x] Google play app

![image](https://user-images.githubusercontent.com/5287596/39668062-02ac9706-50c4-11e8-8a78-1a8d28206a78.png)

For app icon we might use something like https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by tenhobi** [comment]
Would you like to make something, @vojtechdalecky ?

**Comment by vojtechdalecky** [comment]
[appIcon.zip](https://github.com/tenhobi/flashcards/files/2036972/appIcon.zip)

**Comment by tenhobi** [comment]
@vojtechdalecky the background is black, not transparent. Is that correct?

**Comment by vojtechdalecky** [comment]
@tenhobi solved [appIcon.zip](https://github.com/tenhobi/flashcards/files/2037256/appIcon.zip)

**Comment by vojtechdalecky** [comment]
<img width="512" alt="background" src="https://user-images.githubusercontent.com/36296407/40518208-bf4e81c2-5fb9-11e8-9721-83aa86dec1e4.png">
